### PR TITLE
Add `T-T` as a crying emoticon

### PR DESCRIPTION
**Pull request by Dlurak**

### CODE REVIEW

**Comment by wooorm** [comment]
Heya! Cool that you want to help!

Files here are generated. See https://github.com/wooorm/emoticon/blob/main/script/build-data.js for some info on how that happens.
That means your changes will be ignored. Changes have to go into the source files, too!

**Comment by Dlurak** [comment]
Oh I didn't notice that `index.js` is generated. As `T-T` is totally different from the Eyes + Nose + Mouth approach I think it's necessary that there can be totally different faces for one category.  
Something like this:
```json
{
  "cry": [
    ["eyesNormal", "drop", "noseOptional", "mouthNotPositive"],
    [["T"], ["-"], ["T"]]
  ]
}
```

Is this fine for you?

**Comment by wooorm** [comment]
Good point!
If you can make that work, 👍👍

**Comment by wooorm** [comment]
Thanks, releasead in [4.1.0](https://github.com/wooorm/emoticon/releases/tag/4.1.0)!

**Pull request merged**
